In [1]:
import numpy as np

In [6]:
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
array=np.ones(10)
print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [12]:
a=np.arange(10,51)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [13]:
a=np.arange(10,51,2)
print(a)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [15]:
a=np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
one=np.ones((3,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
a=np.random.rand()
print(a)

0.9961554002414057


In [21]:
a=np.random.randint(10,30,25)
print(a)

[19 29 16 10 19 18 23 24 25 13 13 16 27 28 27 25 17 22 14 18 18 19 24 15
 29]


In [23]:
a=np.random.randint(10,30,25).reshape(5,5)
print(a)

[[27 15 29 18 14]
 [25 18 28 21 17]
 [28 10 24 24 22]
 [21 20 18 26 23]
 [23 20 13 14 21]]


In [24]:
a=np.linspace(1,10,20)
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [4]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [6]:
mat[2:6,1:6]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [7]:
mat[3,4]

20

In [8]:
mat[:,1:2]

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [9]:
mat[4,0:5]

array([21, 22, 23, 24, 25])

In [10]:
mat[3:5,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])